version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: devsforadacurva
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

#  CREATE DATABASE devsforadacurva;
#
#  USE devsforadacurva;
#
#  CREATE TABLE pessoa (
#  id INT AUTO_INCREMENT PRIMARY KEY,
#  nome VARCHAR(100) NOT NULL,
#  sobrenome VARCHAR(100) NOT NULL
#  );